In [1]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.decomposition import PCA
import jieba
import numpy as np
from sklearn.impute import SimpleImputer


In [9]:
def mm():
    """
    归一
    :return:
    """
    mm =MinMaxScaler(feature_range=(-1,1))
    data = mm.fit_transform([[90, 2, 10, 40], [60, 4, 15, 45], [75, 3, 13, 46]])

    print(data)
    return None
mm()

[[ 1.         -1.         -1.         -1.        ]
 [-1.          1.          1.          0.66666667]
 [ 0.          0.          0.2         1.        ]]


In [11]:
def stand():
    """
    标准化
    :return:
    """
    std = StandardScaler()
    data = std.fit_transform([[1., -1., 3.], [2., 4., 2.], [4., 6., -1.]])
    print(data)
    print(std.mean_)
    print(std.var_)
    print(std.n_samples_seen_)#样本数
    print('*'*50)
    data1 = std.fit_transform([[-1.06904497, -1.35873244, 0.98058068],
                               [-0.26726124, 0.33968311, 0.39223227],
                               [1.33630621, 1.01904933, -1.37281295]])
    print(std.mean_)
    print(std.var_)
    print(std.n_samples_seen_)
    return None
stand()

[[-1.06904497 -1.35873244  0.98058068]
 [-0.26726124  0.33968311  0.39223227]
 [ 1.33630621  1.01904933 -1.37281295]]
[2.33333333 3.         1.33333333]
[1.55555556 8.66666667 2.88888889]
3
**************************************************
[0. 0. 0.]
[1.         1.         1.00000001]
3


In [ ]:
def im():
    """
    缺失值处理
    :return:
    """
    im = SimpleImputer(missing_values=np.nan,strategy=mean)
    data = im.fit_transform([[1, 2], [np.nan, 3], [7, 6], [3, 2]])
    print(data)
    return None
im()

In [2]:
def var():
    """
    特征选择-删除低方差的特征
    :return:
    """
    #默认只删除方差为0,threshold是方差阈值，删除比这个值小的那些特征
    var=VarianceThreshold(threshold=1)
    data = var.fit_transform([[0, 2, 0, 3],
                              [0, 1, 4, 3],
                              [0, 1, 1, 3]])
    print(data)
    # 获得剩余的特征的列编号
    print('The surport is %s' % var.get_support(True))
    return None
var()

[[0]
 [4]
 [1]]
The surport is [2]


In [4]:
def pca():
    """
    主成分分析进行特征降维
    :return: None
    """
    # n_ components:小数 0~1 90% 业界选择 90~95%
    # 整数   减少到的特征数量
    pca = PCA(n_components=0.8)
    data = pca.fit_transform([[2, 8, 4, 5], [6, 3, 0, 8], [5, 4, 9, 1]])
    print(data)
    return None
pca()

[[ 1.28620952e-15  3.82970843e+00]
 [ 5.74456265e+00 -1.91485422e+00]
 [-5.74456265e+00 -1.91485422e+00]]
